import type { Metadata } from "next";
import { geistSans, geistMono } from "@/ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "E-Catalog Computer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} bg-white antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
